---
- secret:
    name: SECRET_NETBOX_MANAGER
    data:
      PYPI_API_TOKEN: !encrypted/pkcs1-oaep
        - V5oeZwiW4ZOAxAdfWmMZ7PnlD4LKu4dpLhC2hZDy4srdtL9Io5htJOQCUN3c+ZpBxmxDC
          A0g395wEMScy3IDjBkJrQxV77aaOilbmwjmnOOp6/ZnG2UqVBX5bUBSestL1cashRu0S3
          P7Tj8r5qcH0IMU7GEwz0nTDjzoBP1j7UGHEz1b+V7APWG1fWK80uaQsygMOmlmKd3RgqA
          qL64zOV2LaAaHCmvk3ARCZA01h/D26KmeHX9VqnvZ10oUfF0jqJdO8LUccmE96RIPnLd6
          fREouebb0SbLPNpRXE9hdGWtFp/8yomwOFzQXiXEJNP1RX84Nsc2FQoYZik1iD3i1cyZ2
          TCgUm74yzMWuRHXHxibbYCfjWJgsmAhz7pBcHwC6a0QOof+kEPEAZJf+IYahacnaBkf2g
          gezrpLW1w3LjiGnDKbVnI0WD8tGsidT3QPXAkLKKw7yN02i1e2fBe0f15xGkZRY9sQgY+
          LH/qqTKzLJ+eQu9VDYarD7jC4YCayZJKAMFW+85G6dYUM/3kkhzwCRQJUZtuloP+glA1j
          RwQuqNX3BNZgsFAGOacHu24FqH/VmGiamMyxp6FgNZ6RzGiVx25MQzUFJa4ghNwAJ7e7s
          MHcL4qIgOHjEJ6FyVF3BY4zF55lN70UOtQiqakN9BPt4h+29OWdU9FvDnD7DQs=

- job:
    name: netbox-manager-publish-pypi-package
    parent: publish-pypi-package
    secrets:
      - name: secret
        secret: SECRET_NETBOX_MANAGER
        pass-to-parent: true
    vars:
      pypi_twine_executable: "/tmp/venv/bin/python -m twine"

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - flake8
        - mypy
        - python-black
        - yamllint
    periodic-daily:
      jobs:
        - flake8
        - mypy
        - python-black
        - yamllint
    tag:
      jobs:
        - netbox-manager-publish-pypi-package
